// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCam1uNr3Rq35z4qEy8ahoydjnwKTIvaSM',
    appId: '1:768960251163:android:827fcd471f506b37313fbe',
    messagingSenderId: '768960251163',
    projectId: 'kliks-38747',
    storageBucket: 'kliks-38747.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOMshjWZ7pPoZHpJRM_17UUwLtoEHWEZQ',
    appId: '1:768960251163:ios:e8dbe30ad97efa2d313fbe',
    messagingSenderId: '768960251163',
    projectId: 'kliks-38747',
    storageBucket: 'kliks-38747.firebasestorage.app',
    androidClientId: '768960251163-pr4b7cug4japu6628u4g87vpcnmvocf1.apps.googleusercontent.com',
    iosClientId: '768960251163-li2pr1fq362kot2cl3i2f337daiio7us.apps.googleusercontent.com',
    iosBundleId: 'com.app.kliks',
  );

}